from .task1 import deriv
from .task1 import integ
from .task3 import fractional_matrix
from .task3 import gauss
from .task3 import jacobi
from .task4 import kvadr
from .task4 import fun
from .task4 import ravn
from .task4 import Lagrang
from .task4 import approx1
from .task4 import inter
from .task4 import inter1
from .task4 import interp