from .task1 import deriv
from .task1 import integ
from .task3 import fractional_matrix
from .task3 import gauss
from .task3 import jacobi
from .task4 import kvadr
from .task4 import fun
from .task4 import ravn
from .task4 import Lagrang
from .task4 import approx1
from .task4 import inter
from .task4 import inter1
from .task4 import interp
from .task5 import file
from .task5 import c_n
from .task5 import cm_to_inch
from .task5 import start
from .task5 import daub
from .task5 import haar
from .task5 import s
from .task5 import wav
from .task5 import FFT
from .task6 import enter
from .task6 import equation_1
from .task6 import equation_2
from .task6 import Runge_Kutta
from .task6 import Euler_Kauchi
from .task6 import Euler
from .task6 import interpol_diff
from .task6 import approximation_diff
from .task7and8 import temperatura
from .task7and8 import simulated_annealing
from .task7and8 import file
from .task7and8 import random_dist
from .task7and8 import inlet
from .task7and8 import AntColony
from .task7and8 import route_conversion
