from .task1 import inlet_function
from .task1 import deriv
from .task1 import integ
from .task2 import beautiful
from .task2 import el_int
from .task2 import el_float
from .task2 import el_complex
from .task2 import rev_complex
from .task2 import matr
from .task2 import transp
from .task2 import mult
from .task2 import num_mult
from .task2 import add
from .task2 import sub
from .task2 import rec_matrix
from .task2 import det_matrix
from .task3 import fractional_matrix
from .task3 import gauss
from .task3 import jacobi
from .task4 import kvadr
from .task4 import fun
from .task4 import ravn
from .task4 import Lagrang
from .task4 import approx1
from .task4 import inter
from .task4 import inter1
from .task4 import interp
from .task4 import sum_x
from .task4 import sum_y
from .task4 import Lagrang1
from .task4 import Lagrang2
from .task4 import xi
from .task4 import yi
from .task4 import numpy_approximation
from .task5 import file
from .task5 import coef_nesin
from .task5 import cm_to_inch
from .task5 import start
from .task5 import daub
from .task5 import haar
from .task5 import wav
from .task5 import FFT
from .task6 import enter
from .task6 import equation_1
from .task6 import equation_2
from .task6 import Runge_Kutta
from .task6 import Euler_Kauchi
from .task6 import Euler
from .task6 import interpol_diff
from .task6 import approximation_diff
from .task7and8 import temperatura
from .task7and8 import simulated_annealing
from .task7and8 import file
from .task7and8 import random_dist
from .task7and8 import inlet
from .task7and8 import AntColony
from .task7and8 import route_conversion
